add a list of errors for the pre-deploy-check
* this is a rough first pass
* desired format is:
[X] p-event-alerts-e1956ae24f3f965367a0
    Error: ".properties.smtp_selector.enabled.smtp_from"
    Why: "can't be blank"

[X] p-other-alerts-e1956ae24f3f965367a0
    Error: ".properties.smtp_selector.enabled.smtp_from"
    Why: "can't be blank"

[X] p-bosh-33496551a57c8f5c2efd
    Error: missing stemcell
    Why: Required stemcell OS - ubuntu-xenial version 315.13

    Error: some other error
    Why: some reason

* still needs to be tested via command line
* still need to verify that the following comes out while checking each product
[X] p-bosh-33496551a57c8f5c2efd
[✓] p-correctly-configed-tile-abc123
[X] p-event-alerts-e1956ae24f3f965367a0
[✓] p-other-tile-guid-456edf
[X] p-event-other-e1956ae24f3f965367a0

[#165469211]

Signed-off-by: Kira Boyle <kboyle@pivotal.io>